### ISSUE TITLE
Tow truck is not towed

### ISSUE THREAD

**Issue by Adrian400811** [Adrian400811/VehicleSim#2]
Sometimes a tow truck is not being towed after crashing. Probably getting null as "tower"

**Comment by Adrian400811** [comment]
Separate it from the drive method. make it "move to towtruck.getX() - (some distance)" instead. Tow truck disappear will cause null pointer. Make it self-destruct if tow truck = null.

**Comment by Adrian400811** [comment]
``
`java.lang.IllegalStateException: Actor has been removed from the world.
	at greenfoot.Actor.failIfNotInWorld(Actor.java:749)
	at greenfoot.Actor.getX(Actor.java:171)
	at Vehicle.attachTower(Vehicle.java:134)
	at Vehicle.act(Vehicle.java:80)
	at Car.act(Car.java:21)
	at greenfoot.core.Simulation.actActor(Simulation.java:577)
	at greenfoot.core.Simulation.runOneLoop(Simulation.java:540)
	at greenfoot.core.Simulation.runContent(Simulation.java:194)
	at greenfoot.core.Simulation.run(Simulation.java:184)
Caused by: greenfoot.ActorRemovedFromWorld
	at greenfoot.World.removeObject(World.java:466)
	at Vehicle.act(Vehicle.java:95)
	at Truck.act(Truck.java:27)
	... 4 more
```
